spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bookmyevent?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: dev
    password: dev123
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: validate
server:
  port: 8082
services:
  user:
    url: http://localhost:8084
  event:
    url: http://localhost:8081
  seatlock:
    url: http://localhost:8083

